#! /usr/bin/env python3

######################################################################
# This program is free software. It comes without any warranty, to   #
# the extent permitted by applicable law. You can redistribute it    #
# and/or modify it under the terms of the Do What The Fuck You Want  #
# To Public License, Version 2, as published by Sam Hocevar. See     #
# http://www.wtfpl.net/ for more details.                            #
######################################################################

from fileinput import input as fileinput
from albhed.translators import CanonTranslator, FanonTranslator
from albhed.utils import ArgumentHelper, ProperNounDetector

args = ArgumentHelper().parse_args()

Translator = CanonTranslator if args.traditional else FanonTranslator
AlBhed = Translator(args.delimiters[0], args.delimiters[1], args.remove)

if args.nouns:
    dtctr = ProperNounDetector.fromFile(args.nouns)
    AlBhed.addPreprocessor(dtctr.detect)

translate = ArgumentHelper.getTranslateWay(AlBhed, args, "toAlBhed")

for line in fileinput(args.file):
    print(translate(line), end="")
